#! /bin/sh
# /etc/init.d/example

case "$1" in
  start)
    echo "Starting typesetter"
    # run application you want to start
    typesetter &
    ;;
  stop)
    echo "Stopping example"
    # kill application you want to stop
    killall typesetter
    ;;
  *)
    echo "Usage: /etc/init.d/example{start|stop}"
    exit 1
    ;;
esac

exit 0